### ISSUE TITLE
Shopware 5.3.7 checkout error 

### ISSUE THREAD

**Issue by Revo86** [payrexx/shopware-payrexx-gateway#1]
> Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/shop/custom/plugins/PayrexxPaymentGateway/Controllers/Frontend/PaymentPayrexx.php:34 Stack trace: #0 /var/www/shop/engine/Library/Enlight/Controller/Action.php(159): Shopware_Controllers_Frontend_PaymentPayrexx->indexAction() #1 /var/www/shop/engine/Library/Enlight/Controller/Dispatcher/Default.php(530): Enlight_Controller_Action->dispatch('indexAction') #2 /var/www/shop/engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #3 /var/www/shop/engine/Shopware/Kernel.php(191): Enlight_Controller_Front->dispatch() #4 /var/www/shop/vendor/symfony/http-kernel/HttpCache/HttpCache.php(484): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #5 /var/www/shop/engine/Shopware/Components/HttpCache/AppCache.php(268): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Sy in /var/www/shop/custom/plugins/PayrexxPaymentGateway/Controllers/Frontend/PaymentPayrexx.php on line 34

**Comment by ukramer** [comment]
@Revo86 
Vielen Dank für die Meldung. Dies deutet auf eine Fehlkonfiguration im Plugin hin.
Anleitung: https://support.payrexx.com/de/support/solutions/articles/11000041710
Sollte sich das Problem nicht lösen, melden Sie sich bitte an support@payrexx.com oder https://support.payrexx.com.
Beste Grüsse

Thank you for your message. This indicates a misconfiguration in the plugin.
Instructions: https://support.payrexx.com/en/support/solutions/articles/11000041710
If this does not resolve the problem, please contact us at support@payrexx.com or on https://support.payrexx.com.
Best wishes
